### ISSUE TITLE
RedisPool跑不了

### ISSUE THREAD

**Issue by zi41531** [swoole/library#1]
https://github.com/swoole/library/blob/master/examples/redis/base.php
这个代码跑不了，报错如下：

PHP Fatal error:  Uncaught ArgumentCountError: Redis::connect() expects at most 5 parameters, 6 given in @swoole-src/library/core/Database/RedisPool.php:29

php --ri 'swoole'

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.13RC1
Built => Dec  8 2019 02:25:14
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.0.2l  25 May 2017
pcre => enabled
zlib => 1.2.8
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

**Comment by sy-records** [comment]
没复现，redis的connect就是6个参数

**Comment by zi41531** [comment]
> 没复现，redis的connect就是6个参数

https://github.com/swoole/library/blob/master/examples/redis/base.php
我就是这个代码复制下来，单个文件执行的。。。

**Comment by sy-records** [comment]
你自己问题吧，没复现，发下代码

**Comment by zi41531** [comment]
```
<?php

if (!defined('REDIS_SERVER_HOST')) {
    define('REDIS_SERVER_HOST', '172.16.16.107');
    define('REDIS_SERVER_PORT', 6379);
    define('REDIS_SERVER_AUTH', 'xxxxx');
}
use Swoole\Coroutine;
use Swoole\Database\RedisConfig;
use Swoole\Database\RedisPool;
use Swoole\Runtime;
const N = 1024;
Runtime::enableCoroutine();
$s = microtime(true);
Coroutine\run(function () {
    $pool = new RedisPool((new RedisConfig)
        ->withHost(REDIS_SERVER_HOST)
        ->withPort(REDIS_SERVER_PORT)
        ->withAuth(REDIS_SERVER_AUTH)
        ->withDbIndex(0)
        ->withTimeout(1)
    );
    for ($n = N; $n--;) {
        Coroutine::create(function () use ($pool) {
            $redis = $pool->get();
            $result = $redis->set('foo', 'bar');
            if (!$result) {
                throw new RuntimeException('Set failed');
            }
            $result = $redis->get('foo');
            if ($result !== 'bar') {
                throw new RuntimeException('Get failed');
            }
            $pool->put($redis);
        });
    }
});
$s = microtime(true) - $s;
echo 'Use ' . $s . 's for ' . (N * 2) . ' queries' . PHP_EOL;
```

**Comment by zi41531** [comment]
> 你自己问题吧，没复现，发下代码

跟redis、redis扩展有关系吗

**Comment by twose** [comment]
看一下redis扩展的版本

**Comment by zi41531** [comment]
应该是版本的问题，我升级下

**Comment by zi41531** [comment]
请问一下，Swoole\Database里文档写的各种数据库连接池和对象代理的高级封装，支持自动断线重连，是怎么理解，是我不用处理断线重连吗？为什么我用Swoole\Database\PDOPool 出现了大量PDOStatement::execute(): MySQL server has gone away，如果要我来处理断线重连，应该怎么处理。


swoole Swoole =&gt; enabled Author =&gt; Swoole Team <team@swoole.com&gt; Version =&gt; 4.4.13RC1 Built =&gt; Dec 12 2019 09:22:12 coroutine =&gt; enabled epoll =&gt; enabled eventfd =&gt; enabled signalfd =&gt; enabled cpu_affinity =&gt; enabled spinlock =&gt; enabled rwlock =&gt; enabled openssl =&gt; OpenSSL 1.0.2g  1 Mar 2016 pcre =&gt; enabled zlib =&gt; 1.2.11 mutex_timedlock =&gt; enabled pthread_barrier =&gt; enabled futex =&gt; enabled async_redis =&gt; enabled Directive =&gt; Local Value =&gt; Master Value swoole.enable_coroutine =&gt; On =&gt; On swoole.enable_library =&gt; On =&gt; On swoole.enable_preemptive_scheduler =&gt; Off =&gt; Off swoole.display_errors =&gt; On =&gt; On swoole.use_shortname =&gt; On =&gt; On swoole.unixsock_buffer_size =&gt; 8388608 =&gt; 8388608





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"twosee"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月10日(星期二) 下午5:01
收件人:&nbsp;"swoole/library"<library@noreply.github.com&gt;;
抄送:&nbsp;" "<354197364@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [swoole/library] RedisPool跑不了 (#1)




看一下redis扩展的版本

**Comment by twose** [comment]
@zi41531 
如果重试三次以上没有重连成功或处于事务中时会抛出断线错误，一般情况能自动重连
你说的这个可否有复现的方法？
