### ISSUE TITLE
Question about Swoole in cPanel

### ISSUE THREAD

**Issue by fredroo** [swoole/library#101]
How is the right way to use swoole

first i installed
pecl install swoole
inphp.iniAdded in the fileextension=swoole.soThis sentence

with "php - m" show swoole

work with php 7.3 or 8 or only 7.2

i need remove php-fpm or only disable or only above?

**Comment by deminy** [comment]
Latest versions of Swoole only work with PHP 7.1+:

* Swoole 4.6: supports PHP 7.2 to PHP 8.0.
* Swoole 4.5: supports PHP 7.1 to PHP 8.0.
* Swoole 4.4: supports PHP 7.1 to PHP 7.4.

Please make sure you are using PHP 7.1+. If you happen to use PHP 7.1, please install Swoole 4.5 instead (by running `pecl install swoole-4.5.11`).

Swoole and PHP-FPM can be installed/loaded at the same time, but it doesn't mean you can use Swoole under PHP-FPM. Swoole should be used under CLI mode.

**Comment by fredroo** [comment]
only show with php -m in 7.2 and 7.3 version, swoole 4.6, php.ini have extension line

now running php 7.3 and php-fpm, can let this way, gonna work or better remove php-fpm?

**Comment by sy-records** [comment]
You can use two different ini files for cli and php-fpm

**Comment by fredroo** [comment]
in cpanel php.ini is under in /opt/cpanel/ea-php73/root/etc/php.ini is easy apache control

**Comment by AngusDV** [comment]
sudo /opt/cpanel/ea-php80/root/usr/bin/pecl install swoole
but get error 

sh: /root/tmp/pear/swoole/configure: No such file or directory
ERROR: `/root/tmp/pear/swoole/configure --with-php-config=/opt/cpanel/ea-php80/root/usr/bin/php-config --enable-sockets=yes --enable-openssl=no --enable-http2=no --enable-mysqlnd=no' failed

**Comment by AngusDV** [comment]
/opt/cpanel/ea-php80/root/usr/bin/pear install swoole-4.8.8.tgz 
411 source files, building
running: phpize
enable sockets supports? [no] : yes
enable openssl support? [no] : 
enable http2 support? [no] : 
enable mysqlnd support? [no] : 
enable json support? [no] : 
enable curl support? [no] : 
building in /root/tmp/pear/pear-build-rootiqkdss/swoole-4.8.8
running: /root/tmp/pear/swoole/configure --with-php-config=/opt/cpanel/ea-php80/root/usr/bin/php-config --enable-sockets=yes --enable-openssl=no --enable-http2=no --enable-mysqlnd=no --enable-swoole-json=no --enable-swoole-curl=no
sh: /root/tmp/pear/swoole/configure: No such file or directory
ERROR: `/root/tmp/pear/swoole/configure --with-php-config=/opt/cpanel/ea-php80/root/usr/bin/php-config --enable-sockets=yes --enable-openssl=no --enable-http2=no --enable-mysqlnd=no --enable-swoole-json=no --enable-swoole-curl=no' failed

**Comment by AngusDV** [comment]
my problem solved . server administration changed tmp partition.
