### ISSUE TITLE
Deprecated: Constant CURLOPT_BINARYTRANSFER is deprecated in @swoole/library/core/Curl/Handler.php on line 489

### ISSUE THREAD

**Issue by pinerge** [swoole/library#178]
Deprecated: Constant CURLOPT_BINARYTRANSFER is deprecated in @swoole/library/core/Curl/Handler.php on line 489

PHP8.4.1 Swoole6.0.0RC1 使用CURL会出现此弃用提示

![image](https://github.com/user-attachments/assets/697339ce-38a3-4631-9388-5ea6c2d5ecc7)

**Comment by deminy** [comment]
Fixed under swoole/swoole-src#5595.
