### ISSUE TITLE
Some external dependencies still?

### ISSUE THREAD

**Issue by muglug** [swoole/library#2]
`Swoole\ConnectionPool` creates a new instance of `Swoole\Coroutine\Channel` which doesn't exist in the project.

Same goes for `Swoole\Coroutine\Server` which uses the non-existent class `Swoole\Coroutine\Socket`.

And the same goes for `Swoole\Coroutine\Http\Client`.

I discovered this with Psalm (but you could use PHPStan or Phan to find the same).

**Comment by leocavalcante** [comment]
They come from the [PECL extension](https://github.com/swoole/swoole-src). You can add the [Swoole's IDE helper](https://github.com/swoole/ide-helper) and work with [some stubs](https://github.com/leocavalcante/siler/blob/master/psalm.xml.dist#L16).

**Comment by muglug** [comment]
Yeah, but this is meant to be a pure PHP implementation I think?

**Comment by deminy** [comment]
@muglug There are two ways to use it:

* Before Swoole 4.4.13: install it via Composer, assuming that your PHP installation has Swoole 4.x installed and enabled already. (This is a pretty new library; thus the `composer.json` file doesn't yet has this restriction added in the `require` section)
* From Swoole 4.4.13: it's part of the Swoole extension so you can use it directly. The code is written in PHP but compiled into the Swoole extension.

The implementation is written in pure PHP, but it doesn't mean people can use it without any restrictions: it should only be used under CLI mode  with Swoole extension enabled.

This library allows PHP developers to contribute to the Swoole extension directly without development knowledge of C or C++; developers can add Swoole/PHP built-in functions just like creating any other self-defined PHP functions. The Swoole project needs more open source contributors, and people can get involved by contributing more components like the connection pool one, which should be much easier for PHPers.

The Swoole's IDE helper needs to be refactored to work with this new library.

**Comment by muglug** [comment]
Oh, ok sorry - in that case I guess you might want to put that in the readme requirements

**Comment by leocavalcante** [comment]
Still... bring in some code quality provided by static analyzers like Psalm alongside with tests would be a huge plus. No one better than @muglug to make the boot 👀
