### ISSUE TITLE
Where was the Amp driver moved to?

### ISSUE THREAD

**Issue by fabiocarneiro** [swoole/library#88]
There was a file on https://github.com/swoole/library/blob/master/src/Swoole/Driver/Amp.php that was supposed to be the Driver for Amp. It is no longer there. Any idea of where it got moved to?

**Comment by deminy** [comment]
I did a quick search, and there was never such a file:

> git log --all --full-history -- **/Amp.php

**Comment by sy-records** [comment]
The first commit to migrate from swoole-src to library is 19eac0a4, the date is Nov 25, 2019.

But this link  https://github.com/prooph/event-store-client/pull/64#issuecomment-445474265 , commented on 9 Dec 2018

**Comment by fabiocarneiro** [comment]
perhaps there was another repo with the same name before?

**Comment by sy-records** [comment]
> perhaps there was another repo with the same name before?

It should be, so we probably won't find it either...

**Comment by fabiocarneiro** [comment]
@sy-records I think it's safe to assume it was lost forever. Would you be able to check with the maintainers if someone remembers it or if someone can provide some direction on what it used to do or how it worked?

I am using a library that uses Amp, but my main application is running on Swoole. I have been away from PHP for roughly two years and Async in this language is something new for me. It will take some time until I know both libraries well enough to come up with my own solution (if it is even possible).

Right now I have two executables, but for a couple of reasons (like dependencies), it would be desirable to run the Amp dependent part on the Swoole executable.
